# Render 服务配置

services:
  - type: web
    name: jinza-backend
    env: node
    rootDirectory: server
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production